# Generated by Django 5.1.1 on 2024-12-31 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('cost_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('budget', models.IntegerField(default=1000.0, validators=[django.core.validators.MinValueValidator(20)])),
                ('profit', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('sale_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore.item')),
                ('store', models.ManyToManyField(related_name='product', to='GroceryStore.store')),
            ],
        ),
    ]
