# Generated by Django 5.1.1 on 2025-01-01 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
