# Generated by Django 5.1.1 on 2025-01-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryStore', '0002_alter_item_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='profit',
            field=models.IntegerField(default=0.0),
        ),
    ]
