# Generated by Django 5.1.1 on 2025-01-03 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryStore', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
