# Generated by Django 5.1.1 on 2025-01-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryStore', '0006_alter_item_cost_price_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore.item'),
        ),
    ]
